### ISSUE TITLE
flutter

### ISSUE THREAD

**Issue by arunamnaik** [arunamnaik/hello-world#1]
HI,

I have set the environment variable by editing PATH but still getting this error 

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable for where.

**Comment by shivam-rao-official** [comment]
@arunamnaik hey there run flutter doctor and then see what it gives thn send the photos of the error so I can help you with this.
